### ISSUE TITLE
Installation error - sails lift fails after installation 

### ISSUE THREAD

**Issue by cbarlow1993** [emahuni/sails-hook-deep-orm#1]
I installed into my sails project as documented and then when I try lift my sails app i get the following error: 
Versions: 
 `  "sails": "^1.0.2"`
` "sails-hook-orm": "^2.1.0"`
`    "waterline": "^0.13.5"`

```
error: A hook (`deeporm`) failed to load!
error:
error: TypeError: Cannot add property compact, object is not extensible
    at Function.assign (<anonymous>)
    at Function.set (util.js:306:12)
    at Hook.initialize (/home/chris/Documents/code/project/node_modules/sails-hook-deep-orm/index.js:48:30)
    at Hook.wrapper [as initialize] (/home/chris/Documents/code/project/node_modules/@sailshq/lodash/lib/index.js:3275:19)
    at /home/chris/Documents/code/project/node_modules/sails/lib/hooks/index.js:107:18
    at /home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:421:16
    at processQueue (/home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:1565:20)
    at taskComplete (/home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:1588:9)
    at /home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:1612:17
    at /home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:906:16
    at Hook.loadModules (/home/chris/Documents/code/project/node_modules/sails/lib/hooks/index.js:157:14)
    at Hook.wrapper [as loadModules] (/home/chris/Documents/code/project/node_modules/@sailshq/lodash/lib/index.js:3275:19)
    at modules (/home/chris/Documents/code/project/node_modules/sails/lib/hooks/index.js:84:25)
    at runTask (/home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:1621:13)
    at /home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:1559:13
    at processQueue (/home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:1569:13)
    at Object.auto (/home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:1555:5)
    at Hook.load (/home/chris/Documents/code/project/node_modules/sails/lib/hooks/index.js:78:13)
    at Hook.wrapper [as load] (/home/chris/Documents/code/project/node_modules/@sailshq/lodash/lib/index.js:3275:19)
    at loadHook (/home/chris/Documents/code/project/node_modules/sails/lib/app/private/loadHooks.js:212:17)
    at /home/chris/Documents/code/project/node_modules/sails/lib/app/private/loadHooks.js:344:13
    at /home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:1003:9)
    at eachOf (/home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:3145:5)
    at load (/home/chris/Documents/code/project/node_modules/sails/lib/app/private/loadHooks.js:342:17)
    at /home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:3853:24
    at replenish (/home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:931:17)
    at /home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:906:16
    at /home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:3858:13
    at /home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:998:13)
    at /home/chris/Documents/code/project/node_modules/sails/node_modules/async/dist/async.js:906:16

error: Could not load Sails app.
error:
error: Tips:
error:  • First, take a look at the error message above.
error:  • Make sure you've installed dependencies with `npm install`.
error:  • Check that this app was built for a compatible version of Sails.
error:  • Have a question or need help?  (http://sailsjs.com/support)
```

**Comment by emahuni** [comment]
Oh that part of cord is unnecessary I have long moved to a package I developed for tracing and logging, [contrace](https://npmjs.com/package/contrace). I forgot to remove that. So i have removed it completely. 

Tell me how it goes.
